name: bun

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
            bun-version: latest 
      - run: bun install 
      - run: bun lint
      - run: bun next build
      - run: bun start &
      - run: sleep 30
      - run: curl -sI http://localhost:3000/
      - run: killall bun
